### ISSUE TITLE
Haste doesn't work in the overworld

### ISSUE THREAD

**Issue by Zelphy712** [Exploding-Creeper/atlantis#13]
**Description:**
When in the overworld anytime haste is applied to the player via any method I've tried (beacon, botania flask, commands) it immediately goes away.

**To Reproduce**
1. Load up a world
2. Attempt to activate haste via beacon

**Expected behavior**
Haste should be apply able in the overworld.

**Version:**
version1.1.0 of this mod on 1.16.4 of forge, both on a server i run, and client only.

**Comment by relsqui** [comment]
I noticed the same thing with water breathing -- happy to start a new issue for that but it seemed likely to be related. I tested using the snorkel from Artifacts, and disabling Atlantis made it work again.

Minecraft 1.16.5
Forge 36.1.13
Atlantis 1.1.1.0-1.16.5
Artifacts 1.16.5-2.8.4

**Comment by Mysticpasta1** [comment]
this will be fixed when I get a 1.17 release of forge
