### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by AechtRob** [Exploding-Creeper/atlantis#5]
Hi. I have worked out that this mod is causing extreme delays and lag in chunk generation. Are the ores being spawned as structures or something?? (instead of as ores). 

It's so laggy in a pack, I can't really use it at the moment, and I'm assigning 8GB as it is.

**Comment by Mysticpasta1** [comment]
The ores should be spawning as ores it just that it is the water that can cause lag (This is a know issue if you would like to help me solve it then dm me at Mysticpasta1#2562

**Comment by AechtRob** [comment]
I don't mind seeing if I can help; the mod looks interesting..... sent you the connection request on Discord

**Comment by Mysticpasta1** [comment]
unsupport now 1.17 is better :D
